version: '3'
services:
  db:
    image: minispace/db:latest
    container_name: db
    platform: linux/amd64
    pull_policy: always

    volumes:
      - mssqldata:/var/opt/mssql
    ports:
      - "1433:1433"
volumes:
  mssqldata: